name: 3-Tier-Terraform-CI

on: 
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  pre-approval:
    name: Terraform CI Validation
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}

    strategy:
      matrix:
        environment: [dev, stg, prod]

    permissions:
      id-token: write
      contents: read
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::015911059278:role/DevOps-Project
          aws-region: ap-south-1


      - name: Terraform init
        run: terraform init -lock-timeout=300s

      - name: Terraform Format Check 
        run: terraform fmt -check -recursive

      - name: Terraform create & select workspace
        run: |
          terraform workspace select ${{matrix.environment}} || terraform workspace new ${{matrix.environment}}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan 
        run: terraform plan 