name: 3-Tier-Terraform-CD
on: 
  push:
    branches:
      - main

concurrency:
      group: terraform-main
      cancel-in-progress: false

jobs:

  # ======================================================
  # DEV Deployment
  # ======================================================
  deploy-dev:
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}

    environment: dev

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1
      
      - name: Terraform Init 
        run: terraform init

      - name: Terraform create & select workspace
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false tfplan

      - name: Deployment Completed
        run: echo "Bhummmmmm! Deployment Completed, Dev Successfully Worked."

    
 
  # ======================================================
  # Staging Deployment
  # ======================================================
  deploy-stg:
    needs: deploy-dev
    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
    runs-on: ubuntu-latest
    environment: stg

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1
      
      - name: Terraform Init 
        run: terraform init

      - name: Terraform create & select workspace
        run: |
          terraform workspace select stg || terraform workspace new stg

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false tfplan

      - name: Deployment Completed
        run: echo "Bhummmmmm! Deployment Completed, Staging Successfully Worked."


  # ======================================================
  # Production Deployment
  # ======================================================
  deploy-prod:
    needs: deploy-stg
    env:
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::364478544576:role/100DaysOfDevOps
          aws-region: ap-south-1
      
      - name: Terraform Init 
        run: terraform init

      - name: Terraform create & select workspace
        run: |
          terraform workspace select prod || terraform workspace new prod
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false tfplan

      - name: Deployment Completed
        run: echo "Bhummmmmm! Deployment Completed, Production Successfully Worked."